fintech_projec/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("wina.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wina/urls.py
from django.urls import path
from .views import dashboard, CreateTransactionView, load_services, booths_dashboard

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path(
        "transact/",
        CreateTransactionView.as_view(),
        name="create_transaction",
    ),
    path("load-services/", load_services, name="load_services"),
    path("booths", booths_dashboard, name="booths_dashboard"),
]

wina/models.py
from django.db import models

# Create your models here.
class Institution(models.Model):
    name = models.CharField(max_length=100)
    limit = models.IntegerField()
    revenue = models.FloatField()
    def __str__(self):
        return self.name


class Booth(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    services = models.ManyToManyField(Institution, related_name="booths")

    def __str__(self):
        return self.name


class Transaction(models.Model):
    booth = models.ForeignKey(Booth, on_delete=models.CASCADE)
    amount = models.IntegerField()
    service = models.ForeignKey(Institution, on_delete=models.CASCADE)

    def __str__(self):
        return self.booth.name + " - " + str(self.amount)

wina/forms.py
from django import forms
from .models import Transaction, Booth, Institution


class TransactionForm(forms.ModelForm):
    booth = forms.ModelChoiceField(
        queryset=Booth.objects.all(), empty_label="Select a booth"
    )
    service = forms.ModelChoiceField(
        queryset=Institution.objects.none(), empty_label="Select a service"
    )

    class Meta:
        model = Transaction
        fields = ["booth", "service", "amount"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['booth'].label = 'Select Booth'
        self.fields["booth"].widget.attrs["class"] = "text-sky-600 hover:text-white duration-500 bg-white hover:bg-sky-500 focus:ring-4 focus:outline-none focus:ring-sky-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center"

        self.fields['service'].label = 'Select Service'
        self.fields["service"].widget.attrs["class"] = "text-sky-600 hover:text-white duration-500 bg-white hover:bg-sky-500 focus:ring-4 focus:outline-none focus:ring-sky-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center"
        
        self.fields['amount'].label = 'Transaction Amount'
        self.fields["amount"].widget.attrs["class"] = "w-[100%] text-center p-2 rounded-md border border-gray-300"

        # Add placeholder for amount field
        self.fields['amount'].widget.attrs.update({'placeholder': 'Enter amount'})

        if "booth" in self.data:
            try:
                booth_id = int(self.data.get("booth"))
                self.fields["service"].queryset = Booth.objects.get(
                    id=booth_id
                ).services.all()
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields["service"].queryset = self.instance.booth.services.all()
        

wina/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .models import Booth, Transaction, Institution
from .forms import TransactionForm
from django.contrib import messages
from django.views import View
import logging
from django.db.models import Sum, Count

logger = logging.getLogger(__name__)


def dashboard(request):
    transactions = Transaction.objects.all()
    institutions = Institution.objects.all()

    # Calculate the total limit value
    total_limit = institutions.aggregate(total_limit=Sum("limit"))["total_limit"] or 0

    for institution in institutions:
        total_spent = (
            Transaction.objects.filter(service=institution).aggregate(
                total=Sum("amount")
            )["total"]
            or 0
        )
        institution.remaining_value = institution.limit - total_spent
        institution.service_revenue = total_spent * institution.revenue
    total_service_revenue = sum(institution.service_revenue for institution in institutions)

    booth_id = request.GET.get("booth_id")
    service_id = request.GET.get("service_id")

    if booth_id:
        try:
            booth = Booth.objects.get(id=booth_id)
            services_data = [
                {
                    "id": service.id,
                    "name": service.name,
                    "revenue": float(service.revenue),
                }
                for service in booth.services.all()
            ]

            transactions = Transaction.objects.filter(booth=booth)
            if service_id:
                transactions = transactions.filter(service_id=service_id)

            transactions_data = [
                {
                    "id": f"WB{transaction.id:07d}",
                    "service": transaction.service.name,
                    "amount": float(transaction.amount),
                    "taxamount": float(
                        (transaction.amount)
                        - (transaction.amount * 0.15)
                    ),
                }
                for transaction in transactions
            ]

            # Calculate institution transaction counts for the bar chart
            institutions_transactions = (
                transactions.values("service__name")
                .annotate(transaction_count=Count("id"))
                .order_by("-transaction_count")
            )

            institutions_transactions_data = [
                {
                    "institution": item["service__name"],
                    "transaction_count": item["transaction_count"],
                }
                for item in institutions_transactions
            ]

            data = {
                "location": booth.location,
                "services": services_data,
                "transactions": transactions_data,
                "institutions_transactions": institutions_transactions_data,
            }
            return JsonResponse(data)
        except Booth.DoesNotExist:
            logger.warning(f"Booth {booth_id} not found")
            return JsonResponse({"error": "Booth not found"}, status=404)
        except Exception as e:
            logger.error(f"Error processing booth {booth_id}: {str(e)}", exc_info=True)
            return JsonResponse({"error": "Internal server error"}, status=500)
    else:
        booths = Booth.objects.all()
        context = {
            "booths": booths,
            "transactions": transactions,
            "institutions": institutions,
            "total_limit": total_limit,
            "total_service_revenue": total_service_revenue,
        }
        return render(request, "dashboard.html", context)


class CreateTransactionView(View):
    def get(self, request):
        form = TransactionForm()
        # Get the last transaction ID and calculate the next one
        last_transaction = Transaction.objects.last()
        next_transaction_id = f"WB{(last_transaction.id + 1 if last_transaction else 1):07d}"
        return render(
            request,
            "create.html",
            {
                "form": form,
                "next_transaction_id": next_transaction_id,
            },
        )

    def post(self, request):
        form = TransactionForm(request.POST)
        if form.is_valid():
            transaction = form.save()
            transaction_id = f"WB{transaction.id:07d}"
            next_transaction_id = f"WB{(transaction.id + 1):07d}"
            messages.success(
                request, f"Transaction {transaction_id} created successfully."
            )
            # Instead of redirecting, render the same page with the new form and next_transaction_id
            new_form = TransactionForm()  # Create a new, empty form
            return render(
                request,
                "create.html",
                {
                    "form": new_form,
                    "next_transaction_id": next_transaction_id,
                },
            )
        else:
            messages.error(request, "Please correct the errors below.")
            return render(
                request,
                "create.html",
                {
                    "form": form,
                },
            )


def load_services(request):
    booth_id = request.GET.get("booth_id")
    services = Institution.objects.filter(booths__id=booth_id)
    return JsonResponse(list(services.values("id", "name")), safe=False)


def booths_dashboard(request):
    booths = Booth.objects.all()
    booth_transactions = {}

    for booth in booths:
        total_amount = (
            Transaction.objects.filter(booth=booth).aggregate(total=Sum("amount"))[
                "total"
            ]
            or 0
        )
        booth_transactions[booth.name] = total_amount

    context = {
        "booth_transactions": booth_transactions,
    }
    return render(request, "booths.html", context=context)

wina/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>
    <title>
      {% block title %}

      {% endblock %}
    </title>
  </head>
  <body>
    <nav class="bg-white border-gray-200">
      <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <a href="{% url 'dashboard' %}" class="flex items-center space-x-3 rtl:space-x-reverse">
          <img src="https://flowbite.com/docs/images/logo.svg" class="h-8" alt="Wina" />
          <span class="self-center text-2xl font-semibold whitespace-nowrap">Wina FinTech</span>
        </a>
        <div class="flex md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
          <button type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center"><a href="{% url 'create_transaction' %}">Transact</a></button>
          <button data-collapse-toggle="navbar-cta" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200" aria-controls="navbar-cta" aria-expanded="false">
            <span class="sr-only">Open main menu</span>
            <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15" />
            </svg>
          </button>
        </div>
        <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-cta">
          <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white">
            <li>
              <a href="{% url 'dashboard' %}" class="block py-2 px-3 md:p-0 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700" aria-current="page">Home</a>
            </li>
            <li>
              <a href="{% url 'booths_dashboard' %}" class="block py-2 px-3 md:p-0 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700">Booths</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {% block content %}

    {% endblock %}
  </body>
</html>

wina/templates/booths.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}
  Booths | Dashboard
{% endblock %}
{% block content %}
  <section class="w-[90%] mx-auto mt-8">
    <h3 class="text-3xl font-bold mb-6 text-center w-[100%]">Booths Dashboard</h3>
    <div class="grid grid-cols-3 gap-6 mt-8">
      {% for booth_name, total_amount in booth_transactions.items %}
        <div class="bg-white p-4 rounded-md border">
          <h3 class="text-lg font-semibold">{{ booth_name }}</h3>
          <p class="text-xl">K{{ total_amount|floatformat:2|intcomma }}</p>
        </div>
      {% empty %}
        <p>No booth transactions available.</p>
      {% endfor %}
    </div>
  </section>
{% endblock %}

wina/templates/create.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
  {% if messages %}
    <div class="bg-red-900 p-4 absolute top-[15%] w-[80%] ml-[10%] text-white text-center">
      {% for message in messages %}
        <p>{{ message }}</p>
      {% endfor %}
    </div>
  {% endif %}
  <section class="w-[90%] h-[100%] mx-auto mt-8 grid grid-cols-6 gap-3">
    <div class="col-span-2 flex items-center justify-center">
      <div>
        <h6 class="text-xl font-semibold mb-2 text-gray-400">Next Transaction ID</h6>
        <h1 class="text-3xl font-bold mb-6 w-[100%] text-center text-gray-600">{{ next_transaction_id }}</h1>
      </div>
    </div>
    <div class="w-full h-full col-span-4">
      <h1 class="text-3xl font-bold mb-6 w-[100%] text-center">Create Transaction</h1>
      {% if messages %}
        {% for message in messages %}
          <div class="alert error-div {% if message.tags %}
              alert-{{ message.tags }}
            {% endif %}">{{ message }}</div>
        {% endfor %}
      {% endif %}
        <form method="post" id="transactionForm" class="w-[80%] p-4 bg-sky-600 rounded-lg mx-auto">
          {% csrf_token %}
          <div class="grid grid-cols-2 w-[100%] mx-auto">
            <div class="col-span-1 w-full flex items-center justify-center px-5">{{ form.booth }}</div>
            <div class="col-span-1 w-full flex items-center justify-center">{{ form.service }}</div>
            <div class="col-span-2 w-full flex items-center justify-center mt-5">{{ form.amount }}</div>
          </div>
          <div class="w-[50%] mx-auto flex items-center justify-center mt-5">
            <button type="submit" class="bg-white hover:bg-sky-600 text-sky-600 hover:text-white font-bold py-2 px-4 rounded border border-white duration-500">Create Transaction</button>
          </div>
        </form>
      </div>
  </section>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
    $("#id_booth").change(function () {
        var boothId = $(this).val();
        $.ajax({
            url: "{% url 'load_services' %}",
            data: {
                'booth_id': boothId
            },
            success: function (data) {
                $("#id_service").html('<option value="">Select a service</option>');
                data.forEach(function(item) {
                    $("#id_service").append(
                        `<option value="${item.id}">${item.name}</option>`
                    )
                });
            }
        });
    });
</script>
{% endblock %}

wina/templates/dashboard.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}
  Dashboard | Wina Fintech
{% endblock %}

{% block content %}
  <style>
    .fade-in {
      opacity: 0;
      transition: opacity 0.5s ease-in-out;
    }
    .fade-in.active {
      opacity: 1;
    }
    .slide-in {
      transform: translateY(20px);
      opacity: 0;
      transition: transform 0.5s ease-out, opacity 0.5s ease-out;
    }
    .slide-in.active {
      transform: translateY(0);
      opacity: 1;
    }
  </style>

  {% if messages %}
    <div class="bg-red-900 p-4 absolute top-10 w-[80%] ml-[10%] text-white text-center">
      {% for message in messages %}
        <p>{{ message }}</p>
      {% endfor %}
    </div>
  {% endif %}

  <section class="w-[90%] mx-auto mt-8 text-center grid grid-cols-10 gap-5">
    <div class="overflow-hidden col-span-3 flex items-center justify-center">
      <div>
        <canvas class="p-1 ml-40 mr-40" id="chartPie"></canvas>
      </div>
    </div>
    <div class="col-span-7 flex justify-center items-center">
      <div class="w-[95%] mx-auto">
        <h3 class="text-3xl font-bold mb-6">Remaining Amounts</h3>
        <div class="grid grid-cols-3 gap-3 w-[100%]">
          {% for institution in institutions %}
            {% if forloop.counter <= 3 %}
              <div class="p-3 border rounded-md bg-sky-700 text-white">
                <h2 class="font-medium">{{ institution.name }}</h2>
                <div class="grid grid-cols-2 gap-2 mt-3">
                  <div>
                    <p>K{{ institution.remaining_value|floatformat:2|intcomma }}</p>
                    <p class="text-sm">Remaining</p>
                  </div>
                  <div>
                    <p>K{{ institution.service_revenue|floatformat:2|intcomma }}</p>
                    <p class="text-sm">Generated</p>
                  </div>
                </div>
              </div>
            {% elif forloop.counter == 4 %}
              </div>
              <div class="grid grid-cols-2 gap-3 w-[100%] mt-3">
                <div class="p-3 border rounded-md bg-sky-700 text-white col-start-1 col-end-2">
                  <h2 class="font-medium">{{ institution.name }}</h2>
                  <div class="grid grid-cols-2 gap-2 mt-3">
                    <div>
                      <p>K{{ institution.remaining_value|floatformat:2|intcomma }}</p>
                      <p class="text-sm">Remaining</p>
                    </div>
                    <div>
                      <p>K{{ institution.service_revenue|floatformat:2|intcomma }}</p>
                      <p class="text-sm">Generated</p>
                    </div>
                  </div>
                </div>
            {% else %}
              <div class="p-3 border rounded-md bg-sky-700 text-white col-start-2 col-end-3">
                <h2 class="font-medium">{{ institution.name }}</h2>
                <div class="grid grid-cols-2 gap-2 mt-3">
                  <div>
                    <p>K{{ institution.remaining_value|floatformat:2|intcomma }}</p>
                    <p class="text-sm">Remaining</p>
                  </div>
                  <div>
                    <p>K{{ institution.service_revenue|floatformat:2|intcomma }}</p>
                    <p class="text-sm">Generated</p>
                  </div>
                </div>
              </div>
            {% endif %}
          {% empty %}
            <p>No remaining amounts to display.</p>
          {% endfor %}
        </div>        
      </div>
    </div>
  </section>


  {% if user.is_superuser %}
  <!-- Booth DropDowns -->
  <section class="w-[90%] mx-auto mt-8">
    <div class="grid grid-cols-6 gap-6">
      <div class="col-span-1 flex items-center justify-center h-[13rem]">
        <select id="booth_select" class="w-full p-2 mb-6 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500">
          <option value="">Select a booth</option>
          {% for booth in booths %}
            <option value="{{ booth.id }}">{{ booth.name }}</option>
          {% endfor %}
        </select>
      </div>
      <div id="booth_info" class="col-span-5 bg-sky-600 rounded-lg fade-in" style="display: none;">
        <div class="grid grid-cols-4 gap-4 p-4">
          <div class="col-span-1 border rounded-md p-4 h-[13rem] bg-white flex items-center justify-center slide-in">
            <div class="text-center">
              <h3 class="text-xl font-semibold mb-2 text-gray-400">Location</h3>
              <h2 id="booth_location" class="text-gray-600 text-3xl font-bold"></h2>
            </div>
          </div>
          <div class="col-span-1 border rounded-md p-4 h-[13rem] bg-white slide-in flex items-center justify-center">
            <div class="text-center">
              <h3 class="text-xl font-semibold mb-3 text-gray-800">Services</h3>
              <div id="services_container" class="flex flex-col space-y-4">
                <select id="services_select" class="w-full p-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500">
                  <option value="">Select a service</option>
                </select>
              </div>
            </div>
          </div>
          <div class="col-span-2 border rounded-md p-4 h-[13rem] bg-white slide-in flex items-center justify-center">
            <div>
              <div id="service_revenue" class="text-gray-600 text-xl"></div>
            </div>
          </div>
        </div>
      </div>
      <div id="no_booth_selected" class="col-span-5 bg-sky-600 rounded-lg flex items-center justify-center h-[13rem] fade-in">
        <p class="text-white">Please select a booth to view its details.</p>
      </div>
      <div class="col-span-6">
        <div class="grid grid-cols-2 gap-5">
          <div id="chart-container" class="col-span-1 mt-8" style="display: none;">
            <canvas id="transactionsChart"></canvas>
          </div>
          <div class="mt-4 p-4 col-span-1 col-start-2 rounded-md">
            <h3 class="text-xl font-semibold mb-3 text-gray-800">Transactions</h3>
            <div id="transactions_container" class="overflow-x-auto">
              <table class="min-w-full bg-white">
                <thead>
                  <tr>
                    <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">ID</th>
                    <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Service</th>
                    <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Amount</th>
                    <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Amount After Tax</th>
                  </tr>
                </thead>
                <tbody id="transactions_body">
                  <!-- Transactions will be inserted here -->
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  {% endif %}
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script>
    $(document).ready(function () {
      let transactionsChart
    
      function loadBoothData(boothId, serviceId) {
        $.ajax({
          url: '{% url "dashboard" %}',
          data: {
            booth_id: boothId,
            service_id: serviceId
          },
          dataType: 'json',
          success: function (data) {
            console.log('Received data:', data) // Debug log
            if (data.error) {
              console.error('Server returned an error:', data.error)
              alert('An error occurred while loading booth data. Please try again.')
              return
            }
    
            $('#booth_location').text(data.location)
    
            var servicesSelect = $('#services_select')
            servicesSelect.empty().append('<option value="">All services</option>')
    
            if (data.services && data.services.length > 0) {
              $.each(data.services, function (index, service) {
                servicesSelect.append('<option value="' + service.id + '" data-revenue="' + service.revenue + '">' + service.name + '</option>')
              })
    
              servicesSelect.show()
              $('#service_revenue').text('').show()
    
              if (serviceId) {
                servicesSelect.val(serviceId)
                var selectedOption = servicesSelect.find('option:selected')
                var revenue = selectedOption.data('revenue')
                if (revenue !== undefined) {
                  $('#service_revenue').text('Revenue per Kwacha: ' + revenue)
                }
              } else {
                $('#service_revenue').text('')
              }
            } else {
              servicesSelect.hide()
              $('#service_revenue').text('No services available for this booth.').show()
            }
    
            updateTransactionsTable(data.transactions)
            updateTransactionsChart(data.institutions_transactions)
    
            $('#transactions_container').show()
            $('#chart-container').show()
            $('#no_booth_selected').removeClass('active').hide()
            $('#booth_info').show().addClass('active')
            $('.slide-in').addClass('active')
          },
          error: function (jqXHR, textStatus, errorThrown) {
            console.error('AJAX error: ' + textStatus + ' : ' + errorThrown)
            alert('An error occurred while loading booth data. Please try again.')
          }
        })
      }
    
      function updateTransactionsTable(transactions) {
        var transactionsBody = $('#transactions_body')
        transactionsBody.empty()
        if (transactions && transactions.length > 0) {
          $.each(transactions, function (index, transaction) {
            transactionsBody.append('<tr>' + '<td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">' + transaction.id + '</td>' + '<td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">' + transaction.service + '</td>' + '<td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">' + transaction.amount + '</td>' + '<td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">' + transaction.taxamount.toFixed(2) + '</td>' + '</tr>')
          })
        } else {
          transactionsBody.append('<tr><td colspan="5" class="px-6 py-4 text-center">No transactions available for this selection.</td></tr>')
        }
      }
    
      function updateTransactionsChart(institutionsTransactions) {
        const ctx = document.getElementById('transactionsChart').getContext('2d')
    
        if (transactionsChart) {
          transactionsChart.destroy()
        }
    
        const labels = institutionsTransactions.map((item) => item.institution)
        const data = institutionsTransactions.map((item) => item.transaction_count)
    
        transactionsChart = new Chart(ctx, {
          type: 'bar',
          data: {
            labels: labels,
            datasets: [
              {
                label: 'Number of Transactions',
                data: data,
                backgroundColor: 'rgba(54, 162, 235, 0.6)',
                borderColor: 'rgba(54, 162, 235, 1)',
                borderWidth: 1
              }
            ]
          },
          options: {
            responsive: true,
            scales: {
              y: {
                beginAtZero: true,
                title: {
                  display: true,
                  text: 'Number of Transactions'
                }
              },
              x: {
                title: {
                  display: true,
                  text: 'Institutions'
                }
              }
            },
            plugins: {
              title: {
                display: true,
                text: 'Transactions by Institution for Selected Booth'
              }
            }
          }
        })
      }
    
      $('#booth_select').change(function () {
        var boothId = $(this).val()
        if (boothId) {
          loadBoothData(boothId)
        } else {
          $('#booth_info').removeClass('active')
          $('.slide-in').removeClass('active')
          $('#booth_info').hide()
          $('#chart-container').hide()
          $('#no_booth_selected').show().addClass('active')
        }
      })
    
      $('#services_select').change(function () {
        var boothId = $('#booth_select').val()
        var serviceId = $(this).val()
        loadBoothData(boothId, serviceId)
      })
    
      $('#no_booth_selected').addClass('active')
    })
  </script>

  <script>
    let totalLimit = {{ total_limit }};
    let totalRevenue = {{ total_service_revenue }}
    if (isNaN(totalLimit) || totalLimit === undefined) {
        console.error("Total limit is not a valid number:", totalLimit);
        totalLimit = 0;
    }

    const dataPie = {
      labels: ['Total Credit', 'Total Revenue'],
      datasets: [
        {
          label: 'Wina Fintech',
          data: [totalLimit, totalRevenue],
          backgroundColor: ['rgba(0, 123, 187, 0.8)', 'rgba(0, 12, 239, 0.8)'],
          hoverOffset: 4
        }
      ]
    }
    
    const configPie = {
      type: 'pie',
      data: dataPie,
      options: {}
    }
    
    var chartBar = new Chart(document.getElementById('chartPie'), configPie)
  </script>
{% endblock %}